apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: calico
spec:
  description: Profile for deploying calico chart
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: calico
      chart:
        url: https://docs.projectcalico.org/charts
        name: tigera-operator
        version: "v3.20.1"
        defaultValues: |
            replicaCount: 1
