apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policies.magalix.com
spec:
  group: magalix.com
  scope: Cluster
  names:
    plural: policies
    singular: policy
    kind: Policy  
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                enable:
                  type: boolean
                name:
                  type: string
                id:
                  type: string
                description:
                  type: string
                how_to_solve:
                  type: string
                category:
                  type: string
                severity:
                  type: string
                targets:
                  type: object
                  properties:
                    kind:
                      type: array
                      items:
                        type: string
                  required:
                  - kind
                controls:
                  type: array
                  items:
                    type: string
                tags:
                  type: array
                  items:
                    type: string
                parameters:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true                                                 
                    properties:
                      name:
                        type: string
                      type:
                        type: string
                      required:
                        type: boolean
                code:
                  type: string
              required:
              - id
              - name
              - description
              - how_to_solve
              - category
              - severity
              - code