{{- if .Values.policySource.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: policy-library
  namespace: flux-system
spec:
  interval: 10s
  url: {{ .Values.policySource.url }}
  ref:
    tag: {{ .Values.policySource.tag }}
  {{- if .Values.policySource.secretRef }}
  secretRef:
    name: {{ .Values.policySource.secretRef }}
  {{- end }}
{{- end }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: policy-library
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    {{- if .Values.policySource.enabled }}
    name: policy-library
    {{- else }}
    name: flux-system # config repo
    {{- end }}
    namespace: flux-system
  path: {{ .Values.policySource.path }}
  prune: true
  validation: client