apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: alertmanager
spec:
  description: Profile for deploying alertmanager chart
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: alertmanager
      chart:
        url: https://prometheus-community.github.io/helm-charts
        name: alertmanager
        version: "0.12.2"
