SHELL: /bin/bash
.ONESHELL:


OS := $(shell uname | tr '[:upper:]' '[:lower:]')
CONFDIR="${PWD}/.conf"
BINDIR="${PWD}/.bin"
REPODIR="${PWD}/charts"
INFRASTRUCTURE?="kind"


sort-layers:
	@echo "Sorting charts by layers"
	bash .bin/sort-layers.sh

test: 
	@if [ ${INFRASTRUCTURE} = "kind" ]; then\
		echo "Testing kind platform..." && bash .bin/test-platform.sh
	elif [ ${INFRASTRUCTURE} = "gke" ]; then\
		echo "Testing gke platform..." && bash .bin/test-platform.sh
	fi