{{- if .Values.secretsSource.enabled }}
{{- if not .Values.secretsSource.sourceRef }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10s
  url: {{ .Values.secretsSource.url }}
  {{- if or .Values.secretsSource.tag .Values.secretsSource.branch }}
  ref:
    {{- if .Values.secretsSource.tag }}
    tag: {{ .Values.secretsSource.tag }}
    {{- end }}
    {{- if .Values.secretsSource.branch }}
    branch: {{ .Values.secretsSource.branch }}
    {{- end }}
  {{- end }}
  {{- if .Values.secretsSource.secretRef }}
  secretRef:
    name: {{ .Values.secretsSource.secretRef }}
  {{- end }}
{{- end }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m0s
  {{- if not .Values.secretsSource.sourceRef }}
  sourceRef:
    kind: GitRepository
    name: external-secrets
    namespace: external-secrets
  {{- else }}
  sourceRef:
{{- toYaml .Values.secretsSource.sourceRef | nindent 4 }}
  {{- end }}
  path: {{ .Values.secretsSource.path }}
  prune: true
  validation: client
{{- end }}
