external-secrets:
  installCRDs: true

secretsSource:
  enabled: true
  url: ssh://git@github.com/weaveworks/secrets    # url for the git repository that contains the SecretStore, ExternalSecrets CRs
  # tag: v1.0.0                                   # if you would like to download your secrets from specific tag
  branch: main                                    # if you would like to download your secrets from specific branch
  path: ./clusters/secrets/management/            # could be a path to the secrets dir or a kustomization.yaml file for the CRs (SecretStore, ExternalSecret) in the GitRepository
  secretRef: ssh-creds                            # Name of the K8s secret with private repo auth credentials (private key, pub key, known hosts)
  # sourceRef:                                    # Could specify a name for an existing GitSource reference instead of creating a new one
  #   kind: GitRepository
  #   name: external-secrets
  #   namespace: external-secrets
