{{if eq .Values.usePersistence true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "policy-agent.fullname" . }}
  namespace: magalix-system
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.claimStorage }}
{{end}}