apiVersion: v1
kind: Secret
metadata:
  name: {{ include "policy-agent.fullname" . }}
  namespace: magalix-system
type: kubernetes.io/tls
data:
  tls.crt: |
      {{ .Values.certificate | b64enc }}
  tls.key: |
      {{ .Values.key | b64enc }}