apiVersion: v1
kind: Service
metadata:
  name: {{ include "policy-agent.fullname" . }}
  namespace: magalix-system
spec:
  ports:
  - name: https-admission-webhook
    port: 443
    targetPort: webhook
  selector:
    name:  {{ include "policy-agent.fullname" . }}