apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "policy-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "policy-agent.fullname" . }}
webhooks:
  - name: admission.agent.magalix
    clientConfig:
      service:
        namespace: magalix-system
        name: {{ include "policy-agent.fullname" . }}
        path: /admission
      caBundle: {{ .Values.caCertificate | b64enc }}
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiVersions: ["*"]
        apiGroups: ["", "extensions", "apps", "batch", "metrics.k8s.io", "networking.k8s.io"]
        resources: ["nodes", "nodes/stats", "nodes/metrics", "nodes/proxy", "namespaces", "pods", "limitranges", "deployments", "replicationcontrollers", "statefulsets", "daemonsets", "replicasets", "jobs", "cronjobs", "ingresses", "ingressclasses", "services", "networkpolicies"]
      - operations: [ "CREATE", "UPDATE" ]
        apiVersions: ["*"]
        apiGroups: ["", "rbac.authorization.k8s.io", "storage.k8s.io"]
        resources: ["clusterrolebindings", "clusterroles", "roles", "rolebindings", "persistentvolumes", "persistentvolumeclaims", "storageclasses"]
    timeoutSeconds: 5
    failurePolicy: {{ .Values.failurePolicy }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    matchPolicy: Equivalent
    namespaceSelector:
      matchExpressions:
      - key: agent-admission
        operator: NotIn
        values: ["ignore"]