apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: linkerd
spec:
  description: Profile for deploying linkerd chart
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: linkerd
      chart:
        url: https://helm.linkerd.io/stable
        name: linkerd2
        version: "edge-21.9.3"