apiVersion: v1
entries:
  weave-policy-agent:
  - annotations:
      weave.works/category: Policy
      weave.works/links: |
        - name: Upstream Project
          url: https://github.com/weaveworks/policy-agent
      weave.works/operator: "true"
      weave.works/profile: weave-policy
    apiVersion: v2
    appVersion: "1.0"
    created: "2022-04-04T17:53:43.255129131+02:00"
    description: A Weaveworks Helm chart for Kubernetes to configure the policy agent
    digest: 429f89aff1760ab899eb2553fa27e2211247338bbda7a186672b06b350b1286d
    home: https://github.com/weaveworks/profiles-catalog
    icon: https://www.magalix.com/hubfs/Imported%20images/logo-02.png%3Fwidth=560%26name=logo-02-Dec-18-2020-11-24-41-75-AM.png
    keywords:
    - policy
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: support@weave.works
      name: Weaveworks
    name: weave-policy-agent
    sources:
    - https://github.com/weaveworks/policy-agent
    type: application
    urls:
    - https://raw.githubusercontent.com/weaveworks/profiles-catalog/policy-agent/charts/weave-policy-agent-0.2.0.tgz?token=GHSAT0AAAAAABQXJDLLE5G4OD5P6K2LSOXSYSVLYCA
    version: 0.2.0
generated: "2022-04-04T17:53:43.254401843+02:00"
