apiVersion: v2
name: tekton-pipeline
icon: https://avatars2.githubusercontent.com/u/47602533
description: A Weaveworks Helm chart for the Tekton Pipeline Profile
type: application
version: 0.0.1
dependencies:
  - name: tekton-pipeline
    version: "0.29.0"
    repository: "https://cdfoundation.github.io/tekton-helm-chart/"
kubeVersion: ">=1.22.0-0"
home: https://github.com/weaveworks/profiles-catalog
sources:
  - https://cdfoundation.github.io/tekton-helm-chart/

keywords:
- tekton

maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": tekton-pipeline
  "weave.works/category": Deployment
  "weave.works/layer": layer-2
  "weave.works/links": |
    - name: Chart Sources
      url: https://cdfoundation.github.io/tekton-helm-chart/
    - name: Upstream Project
      url: https://github.com/tektoncd/pipeline
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
