apiVersion: v2
name: karpenter
icon: https://repository-images.githubusercontent.com/278480393/dab059c8-caa1-4b55-aaa7-3d30e47a5616
description: A Weaveworks Helm chart for Karpenter, an open-source node provisioning project built for Kubernetes.
type: application
version: 0.0.1
kubeVersion: ">=1.16.0-0"
appVersion: 0.16.1
home: https://github.com/weaveworks/profiles-catalog
sources:
  - https://github.com/aws/karpenter/

keywords:
- karpenter
- node-provisioning

maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": karpenter
  "weave.works/links": |
    - name: Chart Sources
      url: https://github.com/aws/karpenter/tree/main/charts/karpenter
    - name: Upstream Project
      url: https://github.com/aws/karpenter

dependencies:
- name: karpenter
  version: "0.16.1"
  repository: "https://charts.karpenter.sh/"
  condition: karpenter.enabled
