apiVersion: v2
name: tetragon
icon: https://github.com/cilium/tetragon/releases/download/tetragon-cli/logo-dark.png
description: A Weaveworks Helm chart for the tetragon Profile
type: application
version: 0.0.1
dependencies:
  - name: tetragon
    version: "~0.8.3"
    repository: "https://helm.cilium.io"
kubeVersion: ">=1.16.0-0"
home: https://github.com/weaveworks/profiles-catalog
sources:
  - https://helm.cilium.io

keywords:
- tetragon
- security
- runtime
- ebpf

maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": tetragon
  "weave.works/category": Security
  "weave.works/links": |
    - name: Chart Sources
      url: https://github.com/cilium/tetragon
  "weave.works/profile-ci": |
    - "kind"
    - "gke"
